### ISSUE TITLE
Allow configuration of max concurrent clients on server start

### ISSUE THREAD

**Issue by bratao** [ulixee/ulixee#117]
I want to use use a high number of threads to crawl a Website. However, with npx @ulixee/server start, only 10 connections is allowed.

If I start a new remote connection to hero, the connectionToCore is ignored. After a conversation the the Ulixee channel the following snippet was provided to solve this problem:

```
(async () => {
 await HeroCore.start({ maxConncurrentClientCount: 20 });
 const server = new UlixeeServer();
 await server.listen({ port: 8080 });
 ShutdownHandler.register(() => server.close());
})();
```

**Comment by blakebyrnes** [comment]
Fixed in 2.0.0-alpha.9
