### ISSUE TITLE
New scrape instances cannot be opened if a while loop is running.

### ISSUE THREAD

**Issue by paulosllvn** [ulixee/ulixee#128]
Code to replicate: Simply paste it in index.ts and npm start or however you'd like to run it. You will notice that once the counter gets to 300, the websites fail to reload with the new urls. Why is this?

```
    let test = async (a: string) => {
    let url = new URL(a);
    await heros[url.hostname].goto(a);
    let count = 0;
    while(count<300) {
        count++;
        await heros[url.hostname].waitForMillis(100);
        console.log(count)
    }
}

   export const main = async () => {

    let url: string[][] = [["https://realbookie.com.au//racing/greyhounds/ipswich/race-10-1708560-1064029", "https://marantellibet.com/racing/greyhounds/ipswich/race-5-1252359-1022696"], ["https://realbookie.com.au//racing/greyhounds/ipswich/race-10-1708560-1064029", "https://marantellibet.com/racing/greyhounds/ipswich/race-5-1252359-1022696"]];

    url.forEach((array) => {
        array.forEach((item) => {
            let url = new URL(item).hostname;
            if(!(url in heros)) {
                heros[new URL(item).hostname] = new Hero({
                    showChrome: true,
                    viewport: {
                        width: 1280,
                        height: 800,
                    },
                    disableDevtools: true,
                });
            }
        })
    })

    console.log(heros);

    while (url.length > 0) {

        let urlToScrape = url.pop();

        if (urlToScrape) {
            let promises = urlToScrape.map((bookieSite) => {
                return test(bookieSite);
            })
            await Promise.all(promises);
        }
    }
}
```

**Comment by paulosllvn** [comment]
When i run this code, it loads the first two urls in the array (first array item). Then when the loop gets to 300, my expectation is that it will load the next 2 urls on the same hero instance since they have the same domain. There should only be 2 hero instances running where both are being re-used since they have the same domain. 

However, in practice, when the loop gets to 300, when trying to load the next two urls, the browser freezes and is in an infinite loading state. The reason I want to do this is to not have to keep loading new chrome instances for each iteration of my loop when I can re-use an instance if the domain name is the same. Also saves me having to keep logging in on each new load.

**Comment by blakebyrnes** [comment]
The “freeze” issue is it just being done and not closing, since you haven’t instructed it to. I think your issue is you are sending goto to both chrome instances at once, instead of waiting for it to be done with the first loop. You might consider using something like one single concurrency pqueue for each domain.

**Comment by blakebyrnes** [comment]
Is this ok to close? It seemed like it's not a Ulixee issue.

**Comment by paulosllvn** [comment]
Yep cheers
